### ISSUE TITLE
Q.promise using

### ISSUE THREAD

**Issue by eeiaao** [benlau/quickpromise#6]
Hola.
Q.promise's api using is quite unclear. It's totally different from what I've expected having experience with ordinary js promises.
Can you give a little working example? I think it's worth to add it to the library's description too.

**Comment by benlau** [comment]
Hello,

In fact, Quick Promise is a Promise/A+ compliant implementation. So the usage is pretty the same as other implementation except for the resolve / reject function which is built-in with promise object. That is designed to make it consistent with the Promise QML object.

Example usage:
```
var promise = Q.promise();
promise.then(function() { // on filfulled

}, function() { // on rejected

});

promise.resolve(any_value);
promise.resolve(another_promise_object);
promise.resolve(signal);
```

More  example codes are available at : [Example Code](https://github.com/benlau/quickpromise/blob/master/tests/unittests/tst_promisejs_examples.qml)

**Comment by eeiaao** [comment]
Ok, got it. Didn't notice its using in unit tests. The question is closed, thank you!
