### ISSUE TITLE
Qt 5.12 upgrade naming conflicts

### ISSUE THREAD

**Issue by sirhcybe** [benlau/quickpromise#8]
Looks like the native promise implementation in Qt 5.12 caused some naming conflicts. I'd just switch to native promises but Qt's implementation seems to be incorrect (https://forum.qt.io/topic/100261/promise-chaining-in-qml-qt-5-12). It looks like a find and replace fix which I've done on my local copy and will put in a PR for in a bit.

**Comment by benlau** [comment]
I could still use QuickPromise for Qt 5.12. What is the naming conflict?

**Comment by sirhcybe** [comment]
Here's the change that fixed it: https://github.com/sirhcybe/quickpromise/commit/e6418300256c8cef3be7f77819b6889f50632e61
I'm just using the minimal installation and haven't put in a PR because I still need to go over the rest of the code to make sure I didn't break it and all the tests and docs are correct.

**Comment by benlau** [comment]
my bad... In fact, QuickPromise v1.0.9 should have fixed the naming conflict issue on Jan 2019, but I have forgotten to make a release note. It was released on qpm only.

https://github.com/benlau/quickpromise/releases/tag/v1.0.9
